### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [jake-stewart/force-cul.nvim#2]
After setting up, it's the same:

![image](https://github.com/user-attachments/assets/4d166cc5-b37f-473c-9d81-b89fcda99c38)

**Comment by jake-stewart** [comment]
I don't set highlight groups for you. Your colorscheme should do that.

Try `:hi! link CursorLineNr CursorLine` and `:hi! link CursorLineSign CursorLine` and then `:lua require("force-cul").forceUpdate()` to see what I mean.

Chances are whatever colorscheme you are using doesn't have `CursorLineNr` and `CursorLineSign` highlights and so this plugin is useless for it.
